<?php

class AnalysesArretTableSeeder extends Seeder {

	public function run()
	{
        // Uncomment the below to wipe the table clean before populating
        DB::table('analyses_arret')->truncate();

        $analyses_arret = array(
            array('id' => '1','analyse_id' => '1','arret_id' => '265','sorting' => '1'),
            array('id' => '2','analyse_id' => '2','arret_id' => '241','sorting' => '1'),
            array('id' => '3','analyse_id' => '3','arret_id' => '125','sorting' => '1'),
            array('id' => '4','analyse_id' => '4','arret_id' => '192','sorting' => '1'),
            array('id' => '5','analyse_id' => '5','arret_id' => '67','sorting' => '1'),
            array('id' => '6','analyse_id' => '6','arret_id' => '80','sorting' => '1'),
            array('id' => '7','analyse_id' => '6','arret_id' => '75','sorting' => '2'),
            array('id' => '8','analyse_id' => '6','arret_id' => '74','sorting' => '3'),
            array('id' => '9','analyse_id' => '6','arret_id' => '78','sorting' => '4'),
            array('id' => '10','analyse_id' => '6','arret_id' => '77','sorting' => '5'),
            array('id' => '11','analyse_id' => '6','arret_id' => '79','sorting' => '6'),
            array('id' => '12','analyse_id' => '6','arret_id' => '76','sorting' => '7'),
            array('id' => '13','analyse_id' => '6','arret_id' => '81','sorting' => '8'),
            array('id' => '14','analyse_id' => '7','arret_id' => '148','sorting' => '1'),
            array('id' => '15','analyse_id' => '8','arret_id' => '217','sorting' => '1'),
            array('id' => '16','analyse_id' => '10','arret_id' => '1','sorting' => '1'),
            array('id' => '17','analyse_id' => '11','arret_id' => '383','sorting' => '1'),
            array('id' => '18','analyse_id' => '12','arret_id' => '45','sorting' => '1'),
            array('id' => '19','analyse_id' => '13','arret_id' => '283','sorting' => '1'),
            array('id' => '20','analyse_id' => '14','arret_id' => '179','sorting' => '1'),
            array('id' => '21','analyse_id' => '15','arret_id' => '438','sorting' => '1'),
            array('id' => '22','analyse_id' => '15','arret_id' => '56','sorting' => '2'),
            array('id' => '23','analyse_id' => '16','arret_id' => '56','sorting' => '1'),
            array('id' => '24','analyse_id' => '17','arret_id' => '383','sorting' => '1'),
            array('id' => '25','analyse_id' => '18','arret_id' => '438','sorting' => '1'),
            array('id' => '26','analyse_id' => '19','arret_id' => '408','sorting' => '1'),
            array('id' => '27','analyse_id' => '20','arret_id' => '235','sorting' => '1'),
            array('id' => '28','analyse_id' => '21','arret_id' => '208','sorting' => '1'),
            array('id' => '29','analyse_id' => '22','arret_id' => '141','sorting' => '1'),
            array('id' => '30','analyse_id' => '23','arret_id' => '45','sorting' => '1'),
            array('id' => '31','analyse_id' => '24','arret_id' => '42','sorting' => '1'),
            array('id' => '32','analyse_id' => '25','arret_id' => '21','sorting' => '1'),
            array('id' => '33','analyse_id' => '26','arret_id' => '14','sorting' => '1'),
            array('id' => '34','analyse_id' => '27','arret_id' => '61','sorting' => '1'),
            array('id' => '35','analyse_id' => '28','arret_id' => '264','sorting' => '1'),
            array('id' => '36','analyse_id' => '29','arret_id' => '316','sorting' => '1'),
            array('id' => '37','analyse_id' => '30','arret_id' => '208','sorting' => '1'),
            array('id' => '38','analyse_id' => '31','arret_id' => '141','sorting' => '1'),
            array('id' => '39','analyse_id' => '32','arret_id' => '438','sorting' => '1'),
            array('id' => '40','analyse_id' => '33','arret_id' => '443','sorting' => '1'),
            array('id' => '41','analyse_id' => '33','arret_id' => '408','sorting' => '2'),
            array('id' => '42','analyse_id' => '34','arret_id' => '324','sorting' => '1'),
            array('id' => '43','analyse_id' => '35','arret_id' => '262','sorting' => '1'),
            array('id' => '44','analyse_id' => '36','arret_id' => '460','sorting' => '1'),
            array('id' => '45','analyse_id' => '37','arret_id' => '369','sorting' => '1'),
            array('id' => '46','analyse_id' => '37','arret_id' => '235','sorting' => '2'),
            array('id' => '47','analyse_id' => '38','arret_id' => '52','sorting' => '1'),
            array('id' => '48','analyse_id' => '39','arret_id' => '324','sorting' => '1'),
            array('id' => '49','analyse_id' => '40','arret_id' => '367','sorting' => '1'),
            array('id' => '50','analyse_id' => '41','arret_id' => '209','sorting' => '1'),
            array('id' => '51','analyse_id' => '42','arret_id' => '263','sorting' => '1'),
            array('id' => '52','analyse_id' => '43','arret_id' => '208','sorting' => '1'),
            array('id' => '53','analyse_id' => '44','arret_id' => '61','sorting' => '1'),
            array('id' => '54','analyse_id' => '45','arret_id' => '52','sorting' => '1'),
            array('id' => '55','analyse_id' => '46','arret_id' => '37','sorting' => '1'),
            array('id' => '56','analyse_id' => '47','arret_id' => '32','sorting' => '1'),
            array('id' => '57','analyse_id' => '48','arret_id' => '263','sorting' => '1'),
            array('id' => '58','analyse_id' => '49','arret_id' => '480','sorting' => '1'),
            array('id' => '59','analyse_id' => '50','arret_id' => '489','sorting' => '1'),
            array('id' => '60','analyse_id' => '51','arret_id' => '500','sorting' => '1'),
            array('id' => '61','analyse_id' => '52','arret_id' => '517','sorting' => '1'),
            array('id' => '62','analyse_id' => '53','arret_id' => '522','sorting' => '1'),
            array('id' => '63','analyse_id' => '54','arret_id' => '545','sorting' => '1'),
            array('id' => '64','analyse_id' => '55','arret_id' => '546','sorting' => '1'),
            array('id' => '65','analyse_id' => '56','arret_id' => '553','sorting' => '1'),
            array('id' => '66','analyse_id' => '57','arret_id' => '574','sorting' => '1'),
            array('id' => '67','analyse_id' => '58','arret_id' => '595','sorting' => '1'),
            array('id' => '68','analyse_id' => '59','arret_id' => '597','sorting' => '1'),
            array('id' => '69','analyse_id' => '60','arret_id' => '606','sorting' => '1'),
            array('id' => '70','analyse_id' => '63','arret_id' => '607','sorting' => '1'),
            array('id' => '71','analyse_id' => '64','arret_id' => '632','sorting' => '1'),
            array('id' => '72','analyse_id' => '65','arret_id' => '646','sorting' => '1'),
            array('id' => '73','analyse_id' => '66','arret_id' => '654','sorting' => '1'),
            array('id' => '74','analyse_id' => '67','arret_id' => '655','sorting' => '1'),
            array('id' => '75','analyse_id' => '68','arret_id' => '668','sorting' => '1'),
            array('id' => '76','analyse_id' => '69','arret_id' => '698','sorting' => '1'),
            array('id' => '77','analyse_id' => '70','arret_id' => '708','sorting' => '1'),
            array('id' => '78','analyse_id' => '71','arret_id' => '709','sorting' => '1'),
            array('id' => '79','analyse_id' => '72','arret_id' => '710','sorting' => '1'),
            array('id' => '80','analyse_id' => '73','arret_id' => '731','sorting' => '1'),
            array('id' => '81','analyse_id' => '77','arret_id' => '771','sorting' => '1'),
            array('id' => '82','analyse_id' => '78','arret_id' => '773','sorting' => '1'),
            array('id' => '83','analyse_id' => '79','arret_id' => '794','sorting' => '1'),
            array('id' => '84','analyse_id' => '80','arret_id' => '795','sorting' => '1'),
            array('id' => '85','analyse_id' => '82','arret_id' => '815','sorting' => '1'),
            array('id' => '86','analyse_id' => '83','arret_id' => '821','sorting' => '1'),
            array('id' => '87','analyse_id' => '84','arret_id' => '838','sorting' => '1'),
            array('id' => '88','analyse_id' => '85','arret_id' => '858','sorting' => '1'),
            array('id' => '89','analyse_id' => '86','arret_id' => '860','sorting' => '1'),
            array('id' => '90','analyse_id' => '87','arret_id' => '876','sorting' => '1'),
            array('id' => '91','analyse_id' => '88','arret_id' => '909','sorting' => '1'),
            array('id' => '92','analyse_id' => '89','arret_id' => '918','sorting' => '1')
        );

        // Uncomment the below to run the seeder
        DB::table('analyses_arret')->insert($analyses_arret);
	}

}