<?php

class AnalyseBaCategoriesTableSeeder extends Seeder {

	public function run()
	{
        // Uncomment the below to wipe the table clean before populating
        DB::table('analyse_categories')->truncate();

        $analyse_categories = array(
            array('id' => '1','analyse_id' => '1','categories_id' => '48','sorting' => '1'),
            array('id' => '2','analyse_id' => '2','categories_id' => '48','sorting' => '1'),
            array('id' => '3','analyse_id' => '3','categories_id' => '48','sorting' => '1'),
            array('id' => '4','analyse_id' => '4','categories_id' => '48','sorting' => '1'),
            array('id' => '5','analyse_id' => '5','categories_id' => '48','sorting' => '1'),
            array('id' => '6','analyse_id' => '6','categories_id' => '48','sorting' => '1'),
            array('id' => '7','analyse_id' => '7','categories_id' => '48','sorting' => '1'),
            array('id' => '8','analyse_id' => '8','categories_id' => '48','sorting' => '1'),
            array('id' => '9','analyse_id' => '10','categories_id' => '2','sorting' => '1'),
            array('id' => '10','analyse_id' => '11','categories_id' => '2','sorting' => '1'),
            array('id' => '11','analyse_id' => '12','categories_id' => '2','sorting' => '1'),
            array('id' => '12','analyse_id' => '13','categories_id' => '2','sorting' => '1'),
            array('id' => '13','analyse_id' => '14','categories_id' => '2','sorting' => '1'),
            array('id' => '14','analyse_id' => '15','categories_id' => '2','sorting' => '1'),
            array('id' => '15','analyse_id' => '16','categories_id' => '2','sorting' => '1'),
            array('id' => '16','analyse_id' => '17','categories_id' => '2','sorting' => '1'),
            array('id' => '17','analyse_id' => '18','categories_id' => '2','sorting' => '1'),
            array('id' => '18','analyse_id' => '19','categories_id' => '2','sorting' => '1'),
            array('id' => '19','analyse_id' => '20','categories_id' => '2','sorting' => '1'),
            array('id' => '20','analyse_id' => '21','categories_id' => '2','sorting' => '1'),
            array('id' => '21','analyse_id' => '22','categories_id' => '2','sorting' => '1'),
            array('id' => '22','analyse_id' => '23','categories_id' => '2','sorting' => '1'),
            array('id' => '23','analyse_id' => '24','categories_id' => '2','sorting' => '1'),
            array('id' => '24','analyse_id' => '25','categories_id' => '2','sorting' => '1'),
            array('id' => '25','analyse_id' => '26','categories_id' => '2','sorting' => '1'),
            array('id' => '26','analyse_id' => '27','categories_id' => '2','sorting' => '1'),
            array('id' => '27','analyse_id' => '28','categories_id' => '2','sorting' => '1'),
            array('id' => '28','analyse_id' => '29','categories_id' => '2','sorting' => '1'),
            array('id' => '29','analyse_id' => '30','categories_id' => '2','sorting' => '1'),
            array('id' => '30','analyse_id' => '31','categories_id' => '2','sorting' => '1'),
            array('id' => '31','analyse_id' => '32','categories_id' => '2','sorting' => '1'),
            array('id' => '32','analyse_id' => '33','categories_id' => '2','sorting' => '1'),
            array('id' => '33','analyse_id' => '34','categories_id' => '2','sorting' => '1'),
            array('id' => '34','analyse_id' => '35','categories_id' => '2','sorting' => '1'),
            array('id' => '35','analyse_id' => '36','categories_id' => '48','sorting' => '1'),
            array('id' => '36','analyse_id' => '37','categories_id' => '2','sorting' => '1'),
            array('id' => '37','analyse_id' => '38','categories_id' => '2','sorting' => '1'),
            array('id' => '38','analyse_id' => '39','categories_id' => '2','sorting' => '1'),
            array('id' => '39','analyse_id' => '40','categories_id' => '2','sorting' => '1'),
            array('id' => '40','analyse_id' => '41','categories_id' => '2','sorting' => '1'),
            array('id' => '41','analyse_id' => '42','categories_id' => '2','sorting' => '1'),
            array('id' => '42','analyse_id' => '43','categories_id' => '2','sorting' => '1'),
            array('id' => '43','analyse_id' => '44','categories_id' => '2','sorting' => '1'),
            array('id' => '44','analyse_id' => '45','categories_id' => '2','sorting' => '1'),
            array('id' => '45','analyse_id' => '46','categories_id' => '2','sorting' => '1'),
            array('id' => '46','analyse_id' => '47','categories_id' => '2','sorting' => '1'),
            array('id' => '47','analyse_id' => '48','categories_id' => '2','sorting' => '1'),
            array('id' => '48','analyse_id' => '49','categories_id' => '2','sorting' => '1'),
            array('id' => '49','analyse_id' => '50','categories_id' => '48','sorting' => '1'),
            array('id' => '50','analyse_id' => '51','categories_id' => '48','sorting' => '1'),
            array('id' => '51','analyse_id' => '52','categories_id' => '2','sorting' => '1'),
            array('id' => '52','analyse_id' => '53','categories_id' => '48','sorting' => '1'),
            array('id' => '53','analyse_id' => '54','categories_id' => '2','sorting' => '1'),
            array('id' => '54','analyse_id' => '55','categories_id' => '2','sorting' => '1'),
            array('id' => '55','analyse_id' => '56','categories_id' => '48','sorting' => '1'),
            array('id' => '56','analyse_id' => '57','categories_id' => '2','sorting' => '1'),
            array('id' => '57','analyse_id' => '58','categories_id' => '48','sorting' => '1'),
            array('id' => '58','analyse_id' => '59','categories_id' => '2','sorting' => '1'),
            array('id' => '59','analyse_id' => '60','categories_id' => '2','sorting' => '1'),
            array('id' => '60','analyse_id' => '63','categories_id' => '48','sorting' => '1'),
            array('id' => '61','analyse_id' => '64','categories_id' => '2','sorting' => '1'),
            array('id' => '62','analyse_id' => '64','categories_id' => '4','sorting' => '2'),
            array('id' => '63','analyse_id' => '65','categories_id' => '48','sorting' => '1'),
            array('id' => '64','analyse_id' => '66','categories_id' => '2','sorting' => '1'),
            array('id' => '65','analyse_id' => '67','categories_id' => '48','sorting' => '1'),
            array('id' => '66','analyse_id' => '68','categories_id' => '2','sorting' => '1'),
            array('id' => '67','analyse_id' => '69','categories_id' => '48','sorting' => '1'),
            array('id' => '68','analyse_id' => '70','categories_id' => '2','sorting' => '1'),
            array('id' => '69','analyse_id' => '71','categories_id' => '2','sorting' => '1'),
            array('id' => '70','analyse_id' => '72','categories_id' => '2','sorting' => '1'),
            array('id' => '71','analyse_id' => '73','categories_id' => '2','sorting' => '1'),
            array('id' => '72','analyse_id' => '74','categories_id' => '47','sorting' => '1'),
            array('id' => '73','analyse_id' => '75','categories_id' => '2','sorting' => '1'),
            array('id' => '74','analyse_id' => '76','categories_id' => '48','sorting' => '1'),
            array('id' => '75','analyse_id' => '77','categories_id' => '2','sorting' => '1'),
            array('id' => '76','analyse_id' => '78','categories_id' => '2','sorting' => '1'),
            array('id' => '77','analyse_id' => '79','categories_id' => '48','sorting' => '1'),
            array('id' => '78','analyse_id' => '80','categories_id' => '2','sorting' => '1'),
            array('id' => '79','analyse_id' => '81','categories_id' => '48','sorting' => '1'),
            array('id' => '80','analyse_id' => '82','categories_id' => '2','sorting' => '1'),
            array('id' => '81','analyse_id' => '83','categories_id' => '48','sorting' => '1'),
            array('id' => '82','analyse_id' => '89','categories_id' => '48','sorting' => '1'),
            array('id' => '83','analyse_id' => '88','categories_id' => '2','sorting' => '1'),
            array('id' => '84','analyse_id' => '87','categories_id' => '48','sorting' => '1'),
            array('id' => '85','analyse_id' => '85','categories_id' => '48','sorting' => '1'),
            array('id' => '86','analyse_id' => '84','categories_id' => '2','sorting' => '1')
        );

        // Uncomment the below to run the seeder
        DB::table('analyse_categories')->insert($analyse_categories);
	}

}